name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: SpotBugs
      run: mvn -B verify --file pom.xml

    - name: Upload SpotBugs report
      uses: actions/upload-artifact@v3
      with:
        name: spotbugs-report.xml
        path: target/spotbugsXml.xml

    - name: Snyk
      uses: snyk/actions/maven@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --all-projects
    
    - name: Upload Snyk report
      uses: actions/upload-artifact@v3
      with:
        name: snyk-report.json
        path: target/snyk-report.json
